### ISSUE TITLE
ERROR: redis ping: ERR Client sent AUTH, but no password is set

### ISSUE THREAD

**Issue by zgunz42** [golangid/candi#9]
Pada docker compose
```yaml
services:
  redis:
    image: redis:5.0.5-alpine
    container_name: redis
    environment:
      - REDIS_PASSWORD=pass
      - REDIS_PORT=6379
      - REDIS_DB=0
    volumes:
      - redis:/data
    networks:
      - backend
    ports:
      - "6379:6379"
    restart: always
    expose:
      - 6379
```

Untuk environment masih sama seperti yang di buat cli
```
REDIS_READ_DSN=redis://:pass@localhost:6379/0
REDIS_WRITE_DSN=redis://:pass@localhost:6379/0
```

reproduce error:
- `candi init` - buat service di monorepo
- `candi -run`

maka akan keluar error seperti berikut ini (candi v1.10.3)

![image](https://user-images.githubusercontent.com/11344981/150665236-185da695-9071-40eb-981c-286b47aca4ed.png)

**Comment by agungdwiprasetyo** [comment]
sepertinya redisnya itu tidak butuh password, bisa coba dihapus saja passwordnya
```
REDIS_READ_DSN=redis://localhost:6379/0
REDIS_WRITE_DSN=redis://localhost:6379/0
```

jika ingin menggunakan redis dengan password coba docker-compose ini:
```
version: "3"
services:
  redis:
    image: 'redis:5-alpine'
    command: redis-server --requirepass pass
    ports:
      - '6379:6379'
    restart: on-failure
```
